name: snapagram
description: A Flutter app with Firebase authentication
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  google_sign_in: ^6.1.6
  provider: ^6.1.1
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  permission_handler: ^11.1.0
  # Camera and image processing
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  path: ^1.8.3
  image: ^4.1.3
  photo_view: ^0.14.0
  flutter_colorpicker: ^1.0.3
  # DogWalk Dependencies
  google_maps_flutter: ^2.5.0
  firebase_database: ^10.3.0
  location: ^5.0.0
  geolocator: ^10.1.0
  flutter_rating_bar: ^4.0.1
  chips_choice: ^3.0.0
  google_places_flutter: ^2.1.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 