name: snapagram
description: A Flutter app with Firebase authentication
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.5
  google_sign_in: ^6.3.0
  provider: ^6.1.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.9
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  permission_handler: ^11.4.0
  # Camera and image processing
  camera: ^0.10.6
  path_provider: ^2.1.3
  path: ^1.8.3
  image: ^4.2.0
  photo_view: ^0.14.0
  flutter_colorpicker: ^1.0.3
  video_player: ^2.8.7
  # DogWalk Dependencies
  google_maps_flutter: ^2.7.0
  firebase_database: ^10.5.7
  location: ^5.0.3
  geolocator: ^10.1.1
  flutter_rating_bar: ^4.0.1
  chips_choice: ^3.0.0
  google_places_flutter: ^2.1.0
  http: ^1.2.1
  flutter_dotenv: ^5.2.1
  deepar_flutter_plus: ^0.2.0
  flutter_polyline_points: ^2.0.0
  intl: ^0.19.0
  animated_text_kit: ^4.2.2
  carousel_slider: ^4.2.1
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0
  emoji_picker_flutter: ^2.2.0
  image_cropper: ^7.0.0
  uuid: ^4.4.0
  encrypt: ^5.0.3
  crypto: ^3.0.3
  pointycastle: ^3.9.1
  dart_jsonwebtoken: ^2.17.0
  rxdart: ^0.27.7
  flutter_cache_manager: ^3.3.2
  animated_checkmark: ^1.0.1
  confetti: ^0.7.0
  dio: ^5.4.3+1
  flutter_local_notifications: ^17.2.1
  firebase_messaging: ^14.9.4
  shimmer: ^3.0.0
  lottie: ^3.1.2
  timeago: ^3.6.1
  visibility_detector: ^0.4.0+2
  collection: ^1.18.0
  url_launcher: ^6.3.0
  flutter_blurhash: ^0.8.2
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  connectivity_plus: ^6.0.3
  flutter_keyboard_visibility: ^6.0.0
  file_picker: ^8.0.6
  open_filex: ^4.4.0
  geocoding: ^3.0.0
  widget_event: ^1.11.0
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.2
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.15
  mockito: ^5.4.4
  firebase_auth_mocks: ^0.13.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/effects/
    - .env 